[package]
name = "varve-surface"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
varve-core = { path = "../varve-core" }
varve-schema = { path = "../varve-schema" }
varve-logic = { path = "../varve-logic" }
varve-value = { path = "../varve-value" }
thiserror.workspace = true
regex.workspace = true

[dev-dependencies]
proptest.workspace = true
varve-wire = { path = "../varve-wire" }
