[package]
name = "varve-logic"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
varve-core = { path = "../varve-core" }
varve-schema = { path = "../varve-schema" }
varve-value = { path = "../varve-value" }
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
