[package]
name = "m0"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
varve-core = { path = "../../crates/varve-core" }
varve-schema = { path = "../../crates/varve-schema" }
varve-wire = { path = "../../crates/varve-wire" }
serde_json = "1"
