version = 1

[schema]

[[schema.tables]]
id = 0
name = "revisions"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "revision"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "schema"
ty = "Bytes"
storage_ty = "Blob"

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_revisions_by_revision"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 1
name = "surfaces"
primary_key = { columns = [{ table = 1, index = 0 }, { table = 1, index = 1 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "revision"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "surface"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "body"
ty = "Bytes"
storage_ty = "Blob"

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_surfaces_by_revision_and_surface"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }, { column = { table = 1, index = 1 }, op = "Eq", scope = "Local" }]
unique = true
primary_key = true

[[schema.tables]]
id = 2
name = "publications"
primary_key = { columns = [{ table = 2, index = 0 }, { table = 2, index = 1 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "lineage"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "index"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "revision"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "parents"
ty = { List = "String" }
storage_ty = { List = "Text" }

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_publications_by_lineage_and_index"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }, { column = { table = 2, index = 1 }, op = "Eq", scope = "Local" }]
unique = true
primary_key = true
