version = 1

[[migrations]]
id = 7685698228942473440
name = "0000_auth_foundations.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 7108876372962205711
name = "0001_session_metadata.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
id = 2066704883652149974
name = "0002_organizations_teams.sql"
snapshot_name = "0002_snapshot.toml"

[[migrations]]
id = 3894584656004657910
name = "0003_drop_redundant_membership_indexes.sql"
snapshot_name = "0003_snapshot.toml"

[[migrations]]
id = 8727607206337974332
name = "0004_api_tokens.sql"
snapshot_name = "0004_snapshot.toml"

[[migrations]]
id = 3323055327843452823
name = "0005_foreign_keys.sql"
snapshot_name = "0005_snapshot.toml"

[[migrations]]
id = 59429660814426073
name = "0006_revision_draft.sql"
snapshot_name = "0006_snapshot.toml"

[[migrations]]
id = 2864550390107723269
name = "0007_authored_tree.sql"
snapshot_name = "0007_snapshot.toml"
